language: node_js
node_js:
- '0.12'
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo d -g
before_install:
- openssl aes-256-cbc -K $encrypted_4f87ed1ff5e5_key -iv $encrypted_4f87ed1ff5e5_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "杜龙龙"
- git config --global user.email kaixin890312@163.com
