menu:
    博客: /
    简历: /resume.html
    rss: /atom.xml
    github: https://github.com/dolonfly

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# google-analytics:
ga: UA-65933410-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?4c886d1fc6efc87a3896e41f3c76ede9
# cnzz
ca: 1257404288